# Generated by Django 3.0.8 on 2020-08-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conetnt',
            new_name='content',
        ),
    ]
